export default {
    clean: [
        'When your Uber has arrived',
        'Thanks for the invite!',
        'Why are my cousins dating?',
        "I can't finish",
        "I feel like someone is watching me...",
        'The airport has banned your kind of people',
        'Weird flex but okay',
        'When you you pull the reverse card in UNO.',
        'My reaction when I stepped on LEGO.',
        'When you need to go to the bathroom but you only have 5 % battery left on your phone.',
        'My reaction when you’re at work and look at the clock and you still have 7 hours and 59 minutes left.',
        'When there’s a spider in my shoe.',
        'When you notice a typo immediately after you hit “send”.',
        'When someone adds another dish while you’re washing the dishes.',
        'When your friend who owes you money and asks if you can spot them.',
        'When you send a long meaningful text and they reply with “k”.',
        'When I’m told to make a project in REACT.',
        'When Windows asks you to use Microsoft Edge.',
        'When you look at the picture you posted back in highschool.',
        'My reaction when I accidentally like a picture of my crush from 3 years ago.',
        'When you get that piece of popcorn out of your teeth. ',
        'When you order a steak medium and they give you well-done.',
        'Dad says he went to the liquor store to buy milk and cigarettes.',
        'When youre finish pooping and you just notice theres no toilet paper',
        'When youre arguing with your family about how your keyboard collection is not a phase.',
        'When your grandpa starts re-tweeting racist tweets.',
        'When you start choking on an ice cube.',
        'When you tell the girl you like that you log in to Club Penguin without your parents permission.',
        'When your coworker keeps telling you to switch to Mac.',
        'Your favorite power move.',
        'When your mom is about to click your homework folder.',
        'When you get a splinter underneath your nail.',
        'When your crush finds your Sonic fan fic.',
        'My reaction when the soft-shell crab isnt sitting well.',
        'When you find out that the nesquik was really grandpa.',
        'When you realize they no longer sell Shaq Soda.',
        'When Elon Musk whispers sweet nothings in your ear.',
        'When your omelette ends up becoming scrambled eggs.',
        'My reaction when I realize that none of this real and its just a simulation.',
        'When you realize that chicken and T-Rex probably taste the same.',
        'When you get out of the shower and you forgot a towel.',
        'When the beans in Beanie Babies were actually spider eggs.',
        'When your friends want to smash then play Super Smash Bros.',
        'My reaction when I stub my pinky toe.',
        'When youre trying to figure out how magnets work.',
        'When you learn youre adopted.',
        'When your water goes from chill to room temp.',
        'When its 4am and you cant stop looking at memes.',
        'When your dad tells you cant drink the water from the fish bowl.',
        'When you buy a furry suit and your parents look disappointed.',
        'When you post your Sonic fan fic to reddit and no one likes it.'

    ],
    dirty: [
        'Clap my ass cheeks, please',
        'When you walk in on your uncle fucking your dog',
        'Mind if I jack off in front of you?',
        'Oh yeah, suck that, bitch.',
        "I'm about to shit my pants",
        "We don't serve your kind here",

    ]
}