export default {
    clean: ['balloons', 
    'puppies', 
    'apples', 
    'minions', 
    'funny', 
    'silly', 
    'skateboard', 
    'feet', 
    'hands', 
    'screw',
    'fat lip',
    'fire hydrant',
    'backflip',
    'celebrate',
    'run',
    'scared',
    'goon',
    'mafia',
    'clean',
    'drgaon',
    'computer',
    'water',
    'pizza',
    'whacky waving inflatable arm flailing tube men',
    'bank',
    'money',
    'cats',
    'rats',
    'tom',
    'jerry',
    'spongebob',
    'y2k',
    'crazy',
    'basic',
    'dab',
    'dragons',
    'seed',
    'dude',
    'captain',
    'goof',
    'derp',
    'jester'
    ],
    dirty: [
        'ass',
        'fuck you',
        'penis',
        'jack off',
        'middle finger',
        'lick',
        'penatration'
    ]
}